### ISSUE TITLE
Auto disable commandspy on disconect

### ISSUE THREAD

**Issue by lzerokoo** [EvelynSubarrow/Commandspy3#3]
In my server (no premium) the users can connect with my admin account and without login, then they can see all the commands logged in the commandspy config.
Please add a feature that allow to disable the commandspy on disconnect event.

**Comment by EvelynSubarrow** [comment]
Features which facilitate the use of pirated clients are discouraged by bukkitdev. You are, of course, free to patch Commandspy to this end, but I won't be adding such a feature unless a more legitimate use case is presented.
